name: Update GitHub Secret

on:
  push:
    branches:
      - main  # adjust the branch as needed

jobs:
  update_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up 1Password CLI
      run: |
        # Install and configure 1Password CLI
        op --version || sudo apt-get install -y 1password-cli


    - name: Set up GitHub CLI
      run: |
        # Install GitHub CLI
        gh --version || sudo apt-get install -y gh

    - name: Run Update Secret Script
      run: |
        # Run the update_secret.sh script
        ./get_1password_secret.sh
      env:
        OP_SESSION_my: ${{ secrets.OP_SESSION_my }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

