name: Update GitHub Secret

on:
  push:
    branches:
      - main

jobs:
  update_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up 1Password CLI
      run: |
        # Install and configure 1Password CLI
        sudo -s \
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
        gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
        tee /etc/apt/sources.list.d/1password.list
        mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
        tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
        gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        apt update && apt install 1password-cli


    - name: Set up GitHub CLI
      run: |
        # Install GitHub CLI
        gh --version || sudo apt-get install -y gh

    - name: Run Update Secret Script
      run: |
        # Run the update_secret.sh script
        ./get_1password_secret.sh
      env:
        OP_SESSION_my: ${{ secrets.OP_SESSION_my }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
