name: "Setup Secret Lexim Dev Terraform"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update_secret.yml"
      - "envs/lexim-dev/**/*"
      - "modules/**/*"

env:
  TF_LOG: INFO
  

jobs:

  Terraform:
    runs-on: ubuntu-latest
    environment: lexim-dev
    env:
      TF_VAR_service_account_token_1pass: ${{ secrets.service_account_token_1pass }}
      TF_VAR_vault_id: ${{ secrets.vault_id }}
      TF_VAR_uuid_id: ${{ secrets.uuid_id }}
      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: ./envs/lexim-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
        with:
          version: latest
      
      - name: Github Token
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
        
      - name: Setup AWS Profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: 1password-terraform
          region: ${{ secrets.AWS_REGION }}
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
                                    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - name: Terraform version
        run: terraform -v

      - name: Terraform Init
        run: terraform init
        working-directory: ./envs/lexim-dev
        id: init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./envs/lexim-dev

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./envs/lexim-dev
      
      - name: Terraform lock
        id: lock
        run: terraform force-unlock -force 55c03a54-39f7-9351-f27d-e444204fe59e
        working-directory: ./envs/lexim-dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./envs/lexim-dev
        
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve -var="github_repository=${{ github.repository }}"
        working-directory: ./envs/lexim-dev
